server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1 # Remove /auth before route request

        - id: auth-service-oauth2
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**, /login/**
          filters:
            - StripPrefix=0

        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
          filters:
            - StripPrefix=1

        - id: collab-service
          uri: lb://collab-service
          predicates:
            - Path=/collab/**
          filters:
            - StripPrefix=1

        - id: message-service-websocket
          uri: lb:ws://message-service
          predicates:
            - Path=/ws, /webrtc-signal
          filters:
            - StripPrefix=0

        # REST API Route
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1

        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storage/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web.socket: TRACE
    org.springframework.web.reactive.socket: TRACE
    io.netty: DEBUG
    org.springframework.http.client: DEBUG
