server:
  port: 8083

spring:
  application:
    name: message-service

  # Data JPA settings
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL}
  messages:
    basename: i18n/messages
    encoding: UTF-8
  #Kafka settings
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: message-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true # Other service can discover
    fetch-registry: true # Can discover other service
  instance:
    prefer-ip-address: true