server:
  port: 8081
#  servlet:
#    context-path: /project

spring:
  application:
    name: project-service

  # Data JPA settings
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL}
  messages:
    basename: i18n/messages
    encoding: UTF-8
  #Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  cache:
    type: redis
  #Kafka settings
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# JWT config
jwt:
  secret_key: ${JWT_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true # Other service can discover
    fetch-registry: true # Can discover other service
  instance:
    prefer-ip-address: true