server:
  port: 8081
  servlet:
    context-path: /project

spring:
  application:
    name: project-service

  # Data JPA settings
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL}